name: build-android-apk

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
  
env:
  DIRETORIO_APP_MOBILE: './src/IMDB.Mobile'
  DIRETORIO_APK: 'bin/Release/net9.0-android'
  ARQUIVO_APK: 'com.companyname.imdb.mobile.apk'

jobs:
  build-aplicativo-android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: configurar java 17
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 17
          distribution: adopt
          
      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-sdk-prereleases: true

      - name: instalar workload .net maui
        run: dotnet workload install maui

      - name: restaurar pacotes nuget
        run: dotnet restore IMDB.sln

      - name: decodificar certificado
        shell: powershell
        run: |
              [System.Convert]::FromBase64String("${{ secrets.ANDROID_KEYSTORE_BASE64 }}") | Set-Content -Encoding Byte ${{ env.DIRETORIO_APP_MOBILE }}\imdb-clone-app.keystore

      - name: gerar google-services.json
        shell: powershell
        run: |
              [System.Convert]::FromBase64String("${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}") | Set-Content -Encoding Byte ${{ env.DIRETORIO_APP_MOBILE }}\google-services.json

      - name: gerar .apk android
        run: | 
              dotnet publish ${{ env.DIRETORIO_APP_MOBILE }}/IMDB.Mobile.csproj -f net9.0-android -c Release `
              /p:AndroidKeyStore=true `
              /p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEY_ALIAS }} `
              /p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEY_PASSWORD }} `
              /p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} `
              /p:AndroidSigningKeyStore=imdb-clone-app.keystore
      
      - name: listar APK gerado
        run: |
          cd ${{ env.DIRETORIO_APP_MOBILE }}
          cd ${{ env.DIRETORIO_APK }}/publish/
          echo 'Diretório com o resultado do build:'
          pwd
          echo ''
          echo 'Arquivos gerados:'
          ls
          
      - name: gerar artefato do apk
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: '**/*.apk'

        
